name:  Setting a Schedule to Trigger Workflows
on:   #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    Schedule:
        - cron: "5 4 * * *" # https://crontab.guru/
    push:
    pull_request:
        types: [closed,assigned,opened,reopened]


jobs:
    run-github-avtions:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: |
                    pwd