name: Encrypting & Decrypting Files

on:  [push] # https://docs.github.com/en/actions/security-guides/encrypted-secrets
env:
  WF_ENV: available to all jobs
  JOB_ENV: logs jobs all
  WF_ENV_SECRET:  ${{ secrets.WF_ENV }}
  WF_ENV_TOKEN:  ${{ secrets.GITHUB_TOKEN}}

jobs:
  decriptesd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: decript file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSHERE" --output $HOME/sercreto.json encripted.json.gpg
        env:
          PASSHERE: ${{ secrets.GITHUB_TOKEN}}
      - name : print our file
        run: cat $HOME/sercreto.json

  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
  gest_secrets:
    runs-on: ubuntu-latest
    needs: [ 'create_issue' ]
    steps:
      - name: Hello world action

        env: # Or as an environment variable
          super_secret: ${{ secrets.WF_ENV }}
        run: |
          echo "super_secret: ${super_secret}"
          echo "WF_ENV_SECRET: ${WF_ENV_SECRET}"
          echo "WF_ENV_TOKEN: ${WF_ENV_TOKEN}"
