name: Using the setup-node Action

on:  [push, pull_request] #


jobs:
  node-version:
    steps:
        - name: logs node version
          run: node -v
        - uses: actions/setup-node@v1
          with:
            node-version: 6  #'10.x'
        - name: logs node version
          run: node -v