name: . Triggering a Workflow with Github Events
#on: [push,pull_request] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
    push:
    pull_request:
        types: [closed,assigned,opened,reopened]

jobs:
    run-github-avtions:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: |
                    pwd