name: Default & Custom Environment Variables
on:  [push]  #https://docs.github.com/en/actions/learn-github-actions/variables
env:
  WF_ENV: available to all jobs
  JOB_ENV: logs jobs all

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV Variables
        env:
          STEPVER_ONLY: solo para este step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEPVER_ONLY: ${STEPVER_ONLY}"
      - name: Log ENV Variables locals
        run: |
            echo "WF_ENV: ${WF_ENV}"
            echo "JOB_ENV: ${JOB_ENV}"
            echo "STEPVER_ONLY: ${STEPVER_ONLY}"
