name: Using Docker Containers in Jobs

on:  [push, pull_request] #

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
      #env:
      #ports:
      #volumes:
      #options: --cpus 1 --host
    steps:
      - name: los node
        run: |
          node -v 
          cat /etc/os-release
