name: Creating our Own Executable File and Running it in our Steps

on:  [push, pull_request] #
jobs:

  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name:  step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /bin/echo
          args: Hello
      - name:  step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name:  runscript entrypoint
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: script.sh
          args: "algo desde el pipeline"
      

  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users