name: Default & Custom Environment Variables
on:  push  #https://docs.github.com/en/actions/learn-github-actions/variables
env:
  WF_ENV: available to all jobs

jobs:
  log-env:
    runs: ubuntu-latest
    steps:
      - name: Log ENV Variables
        run: |
          echo "${WF_ENV}"
