name: shell commands
on: [push,pull_request]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name:  echo a string
        run: echo $HOME
      - name: multiline script
        run : |
          node -v
          npm -v
      - name: python shell
        run: |
           import platform
           print(platform.processor())
        shell: python
  run-shell-windos:
    runs-on: windows-latest
    steps:
        - name: Dir
          run: Get-Location
        - name: bash Dir
          run : pwd
          shell: bash